---
name: "Buttplug"
description: "Integration with Interface Central"
version: "1.0.0"
slug: "buttplug"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  80/tcp: null
host_network: true
map:
  - ssl
ingress: true
ingress_port: 8000
ingress_stream: true
panel_icon: mdi:fruit-pear
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
privileged:
  - DAC_READ_SEARCH
  - SYS_ADMIN