---
name: "Buttplug"
description: "Integration with Interface Central"
version: "1.0.0"
slug: "buttplug"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  80/tcp: null
host_network: true
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:fruit-pear