name: "Buttplug"
description: "Integration with Interface Central"
version: "1.0.0"
slug: "buttplug"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8000/tcp: 8000
